from cloudbot import hook
import random

warnings = [
"Do not use if you cannot see clearly to read the information in the information booklet.",
"Caution: The contents of this bottle should not be fed to fish.",
"For external use only!",
"Warning: This product can burn eyes.",
"Do not use in shower.",
"Do not use while sleeping.",
"Do not use while sleeping or unconscious.",
"Do not place this product into any electronic equipment.",
"Recycled flush water unsafe for drinking.",
"Shin pads cannot protect any part of the body they do not cover.",
"This product not intended for use as a dental drill.",
"Caution: Do not spray in eyes.",
"Do not drive with sunshield in place.",
"Caution: This is not a safety protective device.",
"Do not use near fire, flame, or sparks.",
"Battery may explore or leak.",
"Do not eat toner.",
"Not intended for highway use.",
"This product is not to be used in bathrooms.",
"May irritate eyes.",
"Eating rocks may lead to broken teeth.",
"Caution! Contents hot!",
"Caution: Hot beverages are hot!",
"Caution: Shoots rubber bands.",
"Warning: May contain small parts.",
"Do not use orally.",
"Please keep out of children.",
"Not suitable for children aged 36 months or less.",
"Do not recharge, put in backwards, or use.",
"Warning: Do not use on eyes.",
"Do not look into laser with remaining eye.",
"Do not use for drying pets.",
"For use on animals only.",
"For use by trained personnel only.",
"Keep out of reach of children and teenagers.",
"Remember, objects in the mirror are actually behind you.",
"Warning: Riders of personal watercraft may suffer injury due to the forceful injection of water into body cavities either by falling into the water or while mounting the craft.",
"Warning: Do not climb inside this bag and zip it up. Doing so will cause injury and death.",
"Do not use as ear plugs.",
"Please store in the cold section of the refrigerator.",
"Warning: knives are sharp!",
"Not for weight control.",
"Twist top off with hands. Throw top away. Do not put top in mouth.",
"Theft of this container is a crime.",
"Do not use intimately.",
"Warning: has been found to cause cancer in laboratory mice.",
"Fragile. Do not drop.",
"Cannot be made non-poisonous.",
"Caution: Remove infant before folding for storage.",
"Excessive dust may be irritating to shin and eyes.",
"Look before driving.",
"Do not iron clothes on body.",
"Do not drive car or operate machinery.",
"For indoor or outdoor use only.",
"Wearing of this garment does not enable you to fly.",
"This door is alarmed from 7:00pm - 7:00am.",
"Beware! To touch these wires is instant death. Anyone found doing so will be prosecuted.",
"Warning: do not use if you have prostate problems.",
"Product will be hot after heating.",
"Do not turn upside down.",
"Do not light in face. Do not expose to flame.",
"Choking hazard: This toy is a small ball.",
"Not for human consumption.",
"May be harmful if swallowed.",
"Using Ingenio cookware to destroy your old pots may void your warranty.",
"Do not attempt to stop the blade with your hand.",
"Do not dangle the mouse by its cable or throw the mouse at co-workers.",
"Warning: May contain nuts.",
"Do not eat.",
"Do not eat if seal is missing.",
"Remove occupants from the stroller before folding it.",
"Access hole only -- not intended for use in lifting box.",
"Warning: May cause drowsiness.",
"Warning: Misuse may cause injury or death.",
"Do not use orally after using rectally.",
"Turn off motor before using this product.",
"Not to be used as a personal flotation device.",
"Do not put in mouth.",
"Remove plastic before eating.",
"Not dishwasher safe.",
"For lifting purposes only.",
"Do not put lit candles on phone.",
"Warning! This is not underwear! Do not attempt to put in pants.",
"Do not wear for sumo wrestling.",
"Safe for use around pets.",
"Do not use house paint on face.",
"Do not drive cars in ocean.",
"Always drive on roads. Not on people.",
"For a limited time only.",
"No stopping or standing.",
"Do not sit under coconut trees.",
"These rows reserved for parents with children.",
"All cups leaving this store, rather full or empty, must be paid for.",
"Malfunction: Too less water.",
"Prescriptions cannot be filled by phone.",
"You could be a winner! No purchase necessary. Details inside.",
"Fits one head.",
"Payment is due by the due date.",
"No small children.",
"Warning: Ramp Ends In Stairs.",
"Take care: new non-slip surface.",
"In case of flood, proceed uphill. In case of flash flood, proceed uphill quickly.",
"Ingredients: Artificially bleached flour, sugar, vegetable fat, yeast, salt, gluten, soya flour, emulsifier 472 (E) & 481, flour treatment agents, enzymes, water. May contain: fruit.",
"100% pure yarn.",
"Some materials may irritate sensitive skin. Please look at the materials if you believe this may be the case. Materials: Covering: 100% Unknown. Stuffing: 100% Unknown.",
"Cleans and refreshes without soap or water. Contains: Water, fragrance & soap.",
"Remove the plastic wrapper.",
"Take one capsule by mouth three times daily until gone.",
"Open packet. Eat contents.",
"Remove wrapper, open mouth, insert muffin, eat.",
"Use like regular soap.",
"Instructions: usage known.",
"Serving suggestion: Defrost.",
"Simply pour the biscuits into a bowl and allow the cat to eat when it wants.",
"In order to get out of car, open door, get out, lock doors, and then close doors.",
"Please include the proper portion of your bill.",
"The appliance is switched on by setting the on/off switch to the 'on' position.",
"For heat-retaining corrugated cardboard technology to function properly, close lid.",
"Optional modem required."
]

@hook.command
def warning(conn, nick):
    return random.choice(warnings)
